name: Build and Deploy

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: yarn install

      - name: Build React app
        run: yarn build

      - name: Build Docker image
        run: docker build -t cosmverse-app .

      - name: Push Docker image to registry
        run: docker push your-docker-registry/cosmverse-app
